const rules = {
	"@typescript-eslint/ban-types": "off",
	"@typescript-eslint/consistent-type-assertions": [ "error", { "assertionStyle": "as" } ],
	"@typescript-eslint/consistent-type-definitions": "error",
	"@typescript-eslint/no-explicit-any": "off",
	"@typescript-eslint/no-misused-promises": "off",
	"@typescript-eslint/no-non-null-asserted-optional-chain": "off",
	"@typescript-eslint/only-throw-error": "off",
	"@typescript-eslint/no-unsafe-argument": "off",
	"@typescript-eslint/no-unsafe-assignment": "off",
	"@typescript-eslint/no-unsafe-call": "off",
	"@typescript-eslint/no-unsafe-member-access": "off",
	"@typescript-eslint/no-unused-vars": [ "warn", { "ignoreRestSiblings": true } ],
	"@typescript-eslint/no-wrapper-object-types": "off",
	"@typescript-eslint/restrict-template-expressions": "off",
	"arrow-parens": "error",
	"arrow-spacing": [ "error", { "before": false, "after": true } ],
	"array-bracket-spacing": [ "error", "never" ],
	"block-spacing": [ "error", "always" ],
	"brace-style": [ "error", "stroustrup", { "allowSingleLine": true } ],
	"comma-spacing": [ "error", { "before": false, "after": true } ],
	"computed-property-spacing": [ "error", "never" ],
	"curly": "error",
	"generator-star-spacing": [ "error", { "before": true, "after": false } ],
	"indent": [ "error", "tab", { "SwitchCase": 1 } ],
	"key-spacing": [ "error", { "beforeColon": false, "afterColon": true } ],
	"keyword-spacing": [ "error", { "before": true, "after": true } ],
	"no-empty": [ "warn", { "allowEmptyCatch": true } ],
	"no-extra-parens": "error",
	"no-extra-semi": "error",
	"no-fallthrough": "off",
	"no-mixed-spaces-and-tabs": "error",
	"no-trailing-spaces": "error",
	"object-curly-spacing": [ "error", "always" ],
	"quotes": [ "error", "double" ],
	"space-before-blocks": "error",
	"space-before-function-paren": [ "error", { "anonymous": "never", "named": "never", "asyncArrow": "always" } ],
	"space-in-parens": [ "error", "never" ],
	"space-infix-ops": "error",
	"template-curly-spacing": [ "error", "never" ],
};

export default rules;
