import { funcAt, funcAtReal, funcBy, funcByReal, funcLen } from './ExpressionFunctionAccess.js';
import { funcNot, funcAnd, funcOr, funcGt, funcLt, funcGe, funcLe, funcEqual, funcNotEqual, funcLike, funcNotLike,
	funcNullco, funcIfThenElse } from './ExpressionFunctionBase.js';
import { funcAdd, funcSub, funcNeg, funcMul, funcDiv, funcPct, funcPow } from './ExpressionFunctionMath.js';

export const operAt = funcAt.clone();
export const operAtReal = funcAtReal.clone();
export const operBy = funcBy.clone();
export const operByReal = funcByReal.clone();
export const operLen = funcLen.clone();
export const operNot = funcNot.clone();
export const operAnd = funcAnd.clone();
export const operOr = funcOr.clone();
export const operGt = funcGt.clone();
export const operLt = funcLt.clone();
export const operGe = funcGe.clone();
export const operLe = funcLe.clone();
export const operEqual = funcEqual.clone();
export const operNotEqual = funcNotEqual.clone();
export const operLike = funcLike.clone();
export const operNotLike = funcNotLike.clone();
export const operNullco = funcNullco.clone();
export const operIfThenElse = funcIfThenElse.clone();
export const operAdd = funcAdd.clone();
export const operSub = funcSub.clone();
export const operNeg = funcNeg.clone();
export const operMul = funcMul.clone();
export const operDiv = funcDiv.clone();
export const operPct = funcPct.clone();
export const operPow = funcPow.clone();
