export const Keywords = [
	'true', 'false',
	'null', 'void',
	'number', 'num',
	'boolean', 'bool',
	'timestamp', 'time',
	'integer', 'int',
	'buffer', 'buf',
	'string', 'str',
	'array',
	'object',
	'function',
	'variable', 'var',
	'constant', 'const',
	'while',
	'if', 'else',
];
